### ISSUE TITLE
webThing does not report type

### ISSUE THREAD

**Issue by atirage** [mozilla-iot/webthing-python#24]
Using the provided SingleThing example, the web thing doesn't seem to provide a valid type to the gateway. The response looks like this:
{"name":"My Lamp",
 "type":"",
 "description":"A web connected lamp",
 "href":"/things/http---raspi0.local-8888-",
 "properties":
......

**Comment by mrstegeman** [comment]
v0.7.0 is intended to be used with the upcoming v0.5 gateway release. The webthing libraries track the [spec](https://iot.mozilla.org/wot/), not the gateway. If you'd like to use this with the 0.4.X gateway releases, you can use the v0.6.X series of this library.
