### ISSUE TITLE
Executing action with inputs errors

### ISSUE THREAD

**Issue by freaktechnik** [mozilla-iot/webthing-python#34]
My webthing has an action with two inputs. I haven't figured out how to read those inputs yet, though that's not that important yet, since it doesn't seem to reach my code.

```
ERROR:tornado.application:Uncaught exception POST /actions (192.168.178.27)
HTTPServerRequest(protocol='http', host='ft-txt.local:8888', method='POST', uri='/actions', version='HTTP/1.1', remote_ip='192.168.178.27')
Traceback (most recent call last):
  File "/home/ftc/apps/0b54347c-f22c-11e8-be35-37e8f1024a53/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/ftc/apps/0b54347c-f22c-11e8-be35-37e8f1024a53/webthing/server.py", line 440, in post
    action = thing.perform_action(action_name, input_)
  File "/home/ftc/apps/0b54347c-f22c-11e8-be35-37e8f1024a53/webthing/thing.py", line 342, in perform_action
    action = action_type['class'](self, input_=input_)
TypeError: __init__() missing 2 required positional arguments: 'thing' and 'name'
ERROR:tornado.access:500 POST /actions (192.168.178.27) 123.35ms
```

**Comment by mrstegeman** [comment]
The constructor for your class needs to initialize `Action` with the `thing` and `name` arguments. For an example (which also uses inputs), [see here](https://github.com/mrstegeman/mpd-webthing/blob/master/python/mpd-webthing.py#L75).

**Comment by freaktechnik** [comment]
So I need to overload the constructor?

**Comment by mrstegeman** [comment]
Correct. The `id_` argument for the base class is not auto-generated by the framework when a new action is requested, so the constructor must be overloaded so that an ID can be generated and passed in.
