### ISSUE TITLE
python 3.5 is a high dependency for lowlevel MPU's

### ISSUE THREAD

**Issue by novski** [mozilla-iot/webthing-python#40]
Im trying to find a sollution for my thesis and one path i followed was an Arduino Industrial 101 as small device hosting a webthing application. I run in to the problem that webthing-arduino is not suiteable for linino based boards and then tried to swap over to the MPU where i found that installing python3 is hard. Even more strange is the fact that after searching around package-managers and paths i found that [mycropython](https://github.com/micropython/micropython) does not support Python 3.5 as it is still on 3.4.  

So that let me to the idea to ask here, if it is realy neccassary to use such high version of python and how to find out what wold be the bare minimum. Considering that a webthing will most likely live on a small device...

**Comment by mrstegeman** [comment]
You might want to check out [webthing-upy](https://github.com/mozilla-iot/webthing-upy). It will probably suit your needs better.

**Comment by novski** [comment]
thanks @mrstegeman i wasn't aware of this possibility. Unfortunately micropython is not available on my controller. I wold have to crosscompile and port it, what i do not concider. 

Let me ask just to go sure.  Do you know what problems may hit me if i try to backport webthing-python to python 2.7?
Are you aware of some blocking changes that will not work?

**Comment by mrstegeman** [comment]
@novski I just released 0.11.1, which supports Python 2.7 and 3.4+.

**Comment by novski** [comment]
Thanks for the support!
