### ISSUE TITLE
Display value of an multilevelsensor

### ISSUE THREAD

**Issue by Runkunkun** [mozilla-iot/webthing-python#54]
I did a multilevelsensor that has 4 read only properties ([Repository](https://github.com/Runkunkun/webthing-bme680-weatherstation)). But the property that gets displayed before clicking on the webthing on the website is 90% the times, when I start the app, the humidity and 10% the air quality. I would like to get 100% of the time the air quality property. 

[First Screen](https://rwth-aachen.sciebo.de/s/l6PdHCodPgcIg6p)
[Second Screen](https://rwth-aachen.sciebo.de/s/rN1VevLBUu6SmTI)

**Comment by mrstegeman** [comment]
I opened a PR for you to fix this: https://github.com/Runkunkun/webthing-bme680-weatherstation/pull/2

**Comment by Runkunkun** [comment]
Thanks a lot really nice of you!
