### ISSUE TITLE
Python IOT Devices

### ISSUE THREAD

**Issue by gatordevin** [mozilla-iot/webthing-python#58]
Hi,
I'm doing a little project to create virtual objects in Unity that can interact with the Mozilla IoT gateway and control devices in your house from the unity environment. Currently, I am running the provided python-webthings code with a few modifications on my laptop. I modified the code to open a server-side socket that then waits for data from the client-side socket which has information on what devices to create. My Unity code then has a client-side socket that on startup sends information about what devices need to be created to the python code. The python code then creates the devices and starts the server. So far this has been working great! I can create as many devices as I want and they will all show up in the Mozilla IoT gateway. 

However, I have been running into a problem where let's say I create two devices UnityLightOne and UnityLightTwo. I run the Unity code it sends these names off to the python code which then says hey I need to create two light objects and start the server using these new light classes. I then went to gateway.local/ and searched for the new devices and added both of them. They work like normal lights, I can set brightness and turn them on and off and it shows up in the terminal on my laptop running the python code indicating that these values are changing. I then stop the Unity code which sends data to the python code telling it to stop the server and the devices then gray out at gateway.local/ indicating that the python-webthings server actually stopped. Then I removed UnityLightOne from unity meaning only UnityLightTwo was present and only that name was sent to the python code to create a light class when I ran the Unity code again. This also told the python-webthings server to start up again and you would expect UnityLightTwo to not be grayed out and UnityLightOne to remain grayed out because that was the device that was sent each of these devices also have their own id and name when they are created. Instead, though UnityLightOne is activated and UnityLightTwo remains grayed out. With a few carefully placed print statements throughout the python-webthings code, I found that the get requests coming from the gateway to the python-webthings server were using a thing_id 0. Correct me if I am wrong but I believe that when you add the device to the gateway it also saves the thing_id as the current position of the device in the JSON data. To verify this I created UnityLightThree and reran the code with UnityLightTwo and UnityLightThree activated. As I suspected, UnityLightOne and UnityLightTwo on the gateway both activated. I was wondering if there was a way to fix this issue so that I can remove whatever devices I want and maybe instead of using index values it uses device titles. 

Thank you for any help you can provide, please let me know if the problem description was too difficult to understand I am happy to answer any questions I just wasn't sure how to explain.

**Comment by mrstegeman** [comment]
Your assessment is exactly right. When the WebThingServer is created, it takes the list of Things passed to it and sets up the REST API endpoints according to their index. So:

* Thing 0 -> `/things/0`
* Thing 1 -> `/things/1`
* ...

The problem, until the 0.12 release, was that there was no unique ID by which to index things, so the best we could do was to use the list index. We now have the `id` field in the thing description, which could potentially be used as a replacement for the index.

However, there has been quite a bit of debate about what that `id` should actually look like. The [W3C spec](https://w3c.github.io/wot-thing-description/#thing) says it has to be a valid URI. However, [our spec](https://iot.mozilla.org/wot/#id-member) leans toward using the full URL of the Thing resource. So, if we were to do that, what would we use, if not the list index?

I'm open to a better solution, but have been unable to come up with one. You could of course fork webthing-python and change the path to be something that works better for you. See [here](https://github.com/mozilla-iot/webthing-python/blob/master/webthing/server.py#L681-L682) and [here](https://github.com/mozilla-iot/webthing-python/blob/master/webthing/server.py#L60-L74) for the relevant code.

**Comment by gatordevin** [comment]
So I did try to change that code 
`            for idx, thing in enumerate(self.things.get_things()):
                #thing.set_href_prefix('{}/{}'.format(self.base_path, idx))
                thing.set_href_prefix('{}/{}'.format(self.base_path, thing.get_title()))`
I know this may not have been proper but I just used the name of the object when it was created and changed the Thing function so that I can pass in a name when I create the class. What I found however was that the tornado ThingHandler class has a get_thing() function that is called on every request from the gateway. The issue with this is even if I changed the href_prefix thus changing the REST endpoint the thing id:
 `self.thing = self.get_thing(thing_id)`
Being passed in, I'm assuming from the gateway, still remains 0 or 1. Even if I tried changing the href_prefix removing the devices from the gateway and adding them back. So I believe that there is also a code change required on the gateway side to allow you to pass in a custom id value and have that be used on get requests rather than just using the index ids that are currently being used. Could you provide a bit more information in that regard?

**Comment by mrstegeman** [comment]
There are definitely no changes necessary on the gateway side. Here's a patch that does what you want:

```patch
diff --git a/webthing/server.py b/webthing/server.py
index e119dec..c2b9a5d 100644
--- a/webthing/server.py
+++ b/webthing/server.py
@@ -63,15 +63,11 @@ class MultipleThings:

         idx -- the index
         """
-        try:
-            idx = int(idx)
-        except ValueError:
-            return None
+        for thing in self.things:
+            if thing.get_title() == idx:
+                return thing

-        if idx < 0 or idx >= len(self.things):
-            return None
-
-        return self.things[idx]
+        return None

     def get_things(self):
         """Get the list of things."""
@@ -678,8 +674,10 @@ class WebThingServer:
             ])

         if isinstance(self.things, MultipleThings):
-            for idx, thing in enumerate(self.things.get_things()):
-                thing.set_href_prefix('{}/{}'.format(self.base_path, idx))
+            for thing in self.things.get_things():
+                thing.set_href_prefix(
+                    '{}/{}'.format(self.base_path, thing.get_title())
+                )

             handlers = [
                 [
@@ -688,44 +686,44 @@ class WebThingServer:
                     dict(things=self.things, hosts=self.hosts),
                 ],
                 [
-                    r'/(?P<thing_id>\d+)/?',
+                    r'/(?P<thing_id>[^/]+)/?',
                     ThingHandler,
                     dict(things=self.things, hosts=self.hosts),
                 ],
                 [
-                    r'/(?P<thing_id>\d+)/properties/?',
+                    r'/(?P<thing_id>[^/]+)/properties/?',
                     PropertiesHandler,
                     dict(things=self.things, hosts=self.hosts),
                 ],
                 [
-                    r'/(?P<thing_id>\d+)/properties/' +
+                    r'/(?P<thing_id>[^/]+)/properties/' +
                     r'(?P<property_name>[^/]+)/?',
                     PropertyHandler,
                     dict(things=self.things, hosts=self.hosts),
                 ],
                 [
-                    r'/(?P<thing_id>\d+)/actions/?',
+                    r'/(?P<thing_id>[^/]+)/actions/?',
                     ActionsHandler,
                     dict(things=self.things, hosts=self.hosts),
                 ],
                 [
-                    r'/(?P<thing_id>\d+)/actions/(?P<action_name>[^/]+)/?',
+                    r'/(?P<thing_id>[^/]+)/actions/(?P<action_name>[^/]+)/?',
                     ActionHandler,
                     dict(things=self.things, hosts=self.hosts),
                 ],
                 [
-                    r'/(?P<thing_id>\d+)/actions/' +
+                    r'/(?P<thing_id>[^/]+)/actions/' +
                     r'(?P<action_name>[^/]+)/(?P<action_id>[^/]+)/?',
                     ActionIDHandler,
                     dict(things=self.things, hosts=self.hosts),
                 ],
                 [
-                    r'/(?P<thing_id>\d+)/events/?',
+                    r'/(?P<thing_id>[^/]+)/events/?',
                     EventsHandler,
                     dict(things=self.things, hosts=self.hosts),
                 ],
                 [
-                    r'/(?P<thing_id>\d+)/events/(?P<event_name>[^/]+)/?',
+                    r'/(?P<thing_id>[^/]+)/events/(?P<event_name>[^/]+)/?',
                     EventHandler,
                     dict(things=self.things, hosts=self.hosts),
                 ],
```

**Comment by gatordevin** [comment]
Awesome! That worked perfectly. I believe I was missing the code change to the Handlers. Thank you so much I was crossing my fingers just to get a response!
