### ISSUE TITLE
Actions in single-thing.py example seem to not be invoked

### ISSUE THREAD

**Issue by senft** [mozilla-iot/webthing-python#62]
Hi,
I start the example single-thing.py. Then I send a POST request using curl:

    curl --header "Content-Type: application/json" -d '{"brightness": 50, "duration": 3232}' http://localhost:8888/actions/fade/

But the perform_action method does not seem to be invoked. I extended the FadeAction like so to make sure:

    class FadeAction(Action):
        def __init__(self, thing, input_):
            Action.__init__(self, uuid.uuid4().hex, thing, 'fade', input_=input_)
            print('init')
        def perform_action(self):
            print('perform')
            time.sleep(self.input['duration'] / 1000)
            self.thing.set_property('brightness', self.input['brightness'])
            self.thing.add_event(OverheatedEvent(self.thing, 102))

Am I doing something wrong?

Thanks in advance!

**Comment by mrstegeman** [comment]
You need to make that a POST request by adding `-X POST` to your `curl` command. You should also probably have `-H 'Accept: application/json'`.

**Comment by senft** [comment]
Same behaviour with

    curl -X POST -H "Content-Type: application/json" -H 'Accept: application/json' -d '{"brightness": 50, "duration": 3232}' http://localhost:8888/actions/fade/

It does (with both commands) seem the detect the request as a POST request:

    2019-11-14 09:39:28,337 web.py:2246 INFO 201 POST /actions/fade/ (127.0.0.1) 1.47ms

**Comment by senft** [comment]
I figured it out. I fed illformed JSON to the action. It should have been something like:

    {"fade": {"input": {"brightness": 50, "duration": 3232}}}

**Comment by mrstegeman** [comment]
Ah, yes. I didn't even notice that, as I just saw the other issues!
