### ISSUE TITLE
Initial value of Web Thing is not respected in gateway after Web Thing restart

### ISSUE THREAD

**Issue by ahayzen** [mozilla-iot/webthing-python#65]
Not sure if I'm just doing this wrong and this is expected behaviour or if it's a bug in webthing-python or the gateway.

# What happened

1) Created a simple web thing light with webthing-python (eg this code http://paste.debian.net/1130662/ )
2) Start gateway
3) Start web thing
4) Add light to gateway (notice it starts in the Off state)
5) Toggle the light to be On in the gateway (notice the console of the web thing states it has been changed)
6) Stop the web thing (Ctrl+C the web thing), notice that it fades out in the gateway to show it is disconnected
7) Start the web thing again
8) Notice that once the gateway connects to the web thing, the state remains On, even though the initial value of the web thing is Off

# What I expected to happen

At step 8 for the light to change to the Off state in the gateway as the web thing has been restarted and has set the initial value to Off.

# Workaround

Once the gateway has connected, if notify_of_external_update is used to toggle the state from Off -> On -> Off then the gateway correctly picks up the state as Off.

Note in my code example uncomment the commented code to see this in action.

**Comment by mrstegeman** [comment]
I think this may be an issue with your code. I can reproduce using your code, but if I switch to the `single-thing.py` example, things work as expected. Can you confirm?

**Comment by ahayzen** [comment]
Thanks for the prompt response.

With `single-thing.py` I am able to reproduce this eg
1) Start gateway and single-thing.py
2) Notice that single-thing light starts with On state and 50% power
3) Turn the light Off
4) Stop the single-thing.py
5) Start the single-thing.py
6) Notice that gateway shows light still in Off state and not On with 50% power

Note I'm using gateway 0.10 (I see 0.11 has just been released :-) ) and for the python part webthing==0.12.1.  Also this is using the docker version of gateway.  Maybe updating will change things...

**Comment by mrstegeman** [comment]
Hmm, potentially. 0.11 will officially be released on Monday or Tuesday, so maybe give it a shot again at that point? I don't see anything obviously wrong with your code.

**Comment by ahayzen** [comment]
OK, I will see if 0.11 changes anything when it's available from dockerhub :-)

Note that I am not restarting the gateway within the steps here and only restarting the web thing, it seems that the gateway doesn't "read" the value of the web thing when it comes back online after being in an offline state.

**Comment by ahayzen** [comment]
I've also found that for the `single-thing.py` example, when the issue happens if you refresh the browser showing the gateway it solves the issue.  But this does not work with my example :-/

**Comment by mrstegeman** [comment]
Ah! Something just occurred to me. When you add your web things to the gateway, are you adding them manually (e.g. by IP address), or are you using the auto-detected devices that show up?

**Comment by mrstegeman** [comment]
I found (and fixed) the issue.

If you replace `server.start()` with the following, things work as they should:

```python
try:
    server.start()
except KeyboardInterrupt:
    server.stop()
```

The reason is that this cleanly shuts everything down, causing a proper "service down" event for the mDNS service, which the add-on watches for and handles.

**Comment by ahayzen** [comment]
@mrstegeman ah, of course ! That makes sense ! With 0.11 and ensuring the server is closed correctly, this now works as expected. Thanks ! :-)
