### ISSUE TITLE
Webthing not found

### ISSUE THREAD

**Issue by meatalhead** [mozilla-iot/webthing-python#68]
When I initially ran the single-thing.py example it worked first time, however it's since stopped working and I can't seem to get any webthings to be detected by my gateway. I think I'm just missing something obvious, please could someone suggest a few things to check? Thanks.

**Comment by mrstegeman** [comment]
```
pip3 install webthing
python3 example/single-thing.py
```

Or, if you've cloned this repo and are working directly inside the directory:

```
PYTHONPATH=. python3 example/single-thing.py
```
