### ISSUE TITLE
Multiple Multiple Things

### ISSUE THREAD

**Issue by meatalhead** [mozilla-iot/webthing-python#71]
Is there any good practice or examples of what we should change when adding various different python webthings? Do we just need to change the name, url and port?

**Comment by mrstegeman** [comment]
It depends on what you mean by multiple things. You could use the `MultipleThings` class to add as many things as you want to a single server.

If, instead, you want to run multiple instances, you need to:
1. Use a different port
2. Your things should all _technically_ have different IDs.

**Comment by meatalhead** [comment]
It's multiple servers, anyone know of a good system for allocating port numbers? Or just keep track of the ones you have used?

**Comment by mrstegeman** [comment]
I would just start at some number, e.g. 8000, and increment for each one.

**Comment by meatalhead** [comment]
Thanks
