### ISSUE TITLE
Failure to start an example "single-thing.py

### ISSUE THREAD

**Issue by andrius-v** [mozilla-iot/webthing-python#72]
I've installed library today and tried to run an example. Got this error:

> 
> Traceback (most recent call last):
>   File "single-thing.py", line 118, in <module>
>     run_server()
>   File "single-thing.py", line 106, in run_server
>     server.start()
>   File "/usr/local/lib/python3.7/dist-packages/webthing/server.py", line 864, in start
>     server='{}.local.'.format(socket.gethostname()))
> TypeError: __init__() got an unexpected keyword argument 'address'

Done some digging, checked the constructor of zeroconf ServiceInfo here:
https://github.com/jstasiak/python-zeroconf/blob/master/zeroconf/__init__.py
and then changed the line number 859 in server.py from this
> address=socket.inet_aton(get_ip()),

to this
> addresses=[socket.inet_aton(get_ip())],

and then example started working as expected.

zeroconf version 0.27.0
ifaddr version 0.1.6
python version 3.7.3

**Comment by mrstegeman** [comment]
Thank you for bringing this up! This is fixed in v0.13.1.
