### ISSUE TITLE
Can't find Web Things

### ISSUE THREAD

**Issue by assman** [mozilla-iot/webthing-python#77]
I have defined a few web things in python and when I run the server, my gateway is not able to find the web things. In order to verify if something was wrong with my implementation of the web things, i downloaded the single thing example from the repo and ran that. Turns out that my gateway can't find the example thing either. My gateway is running on a raspberry pi in a docker container with the `--network=host` flag. 

Any ideas on how to go about troubleshooting or suggestions?

**Comment by mrstegeman** [comment]
Is there a firewall running on either side that may be blocking the mDNS discovery and/or the web server?

You can always add your things manually by clicking "Add by URL..." on the thing discovery page.

**Comment by assman** [comment]
Sorry, where is the Add by URL option? 

![no devices found](https://user-images.githubusercontent.com/14093665/95149803-692f8c00-07b9-11eb-901a-50a1482f8fb4.png)

**Comment by mrstegeman** [comment]
Ah, that’s the problem. You need to install the Web Thing add-on for that to appear, and also for discovery to work.

**Comment by assman** [comment]
Understood. Able to discover it now. Thank your for your help, greatly appreciated.
