### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by bphermansson** [mozilla-iot/webthing-python#8]
Tried to run the code but failed:

```
Traceback (most recent call last):
  File "single-thing.py", line 4, in <module>
    from webthing import Action, Event, Property, Thing, WebThingServer, Value
ImportError: cannot import name Value
```

**Comment by mrstegeman** [comment]
How are you running it? What I do is the following (from inside `webthing-python/`):

```shell
PYTHONPATH=. python3 example/single-thing.py
```

**Comment by bphermansson** [comment]
Ok, that solves it. I tried to copy and paste the code into a new file. Now I instead tried to clone the code with Git and used your command line, then it worked. Thanks!
