### ISSUE TITLE
unexpected keyword argument 'metadata'`

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/webthing-python#80]
On its own the single thing example works fine. But when I try to combine this code inside an addon, I get `TypeError: __init__() got an unexpected keyword argument 'metadata'`.

I've been trying to find out what that means, but havent gotten beyond tradind that error for others.

**Comment by mrstegeman** [comment]
It means you're passing a `metadata=<something>` argument to a constructor that wasn't expecting it.

**Comment by flatsiedatsie** [comment]
But I haven't changed the example code. How can the library accept it if called from __main__ but not if called from inside a class init?

If I modify the code to have the metadata dictionary be outside of the structure...
```
        
        self.thing = Thing(
            'urn:dev:ops:candlecam-1234',
            'Candle cam',
            ['VideoCamera'],
            'Candlecam test description'
        )

        met = {'@type': 'VideoProperty',
                         'title': 'Stream',
                         'type': 'null',
                         'description': 'Video stream',
                         'links': [{
                             'rel': 'alternative',
                             'href': 'http://192.168.2.167:8888/media/stream/mjpg',
                             'mediaType': 'x-motion-jpeg'
                         }]
                     }
                     
        self.video_property = Property(self.thing,'stream',Value(None),met)

        self.thing.add_property(self.video_property)
        
        self.server = WebThingServer(SingleThing(self.thing), port=8888)
```
...then I get a different error:

```
    self.video_property = Property(self.thing,'stream',Value(None),met)
TypeError: __init__() takes 4 positional arguments but 5 were given
```

**Comment by mrstegeman** [comment]
I'm guessing you're getting your `Property` classes mixed up.
* webthing library: https://github.com/WebThingsIO/webthing-python/blob/master/webthing/thing.py#L10
* gateway_addon library: https://github.com/WebThingsIO/gateway-addon-python/blob/master/gateway_addon/property.py#L9

**Comment by flatsiedatsie** [comment]
That was it. Thank you.
